### Numpy

In [3]:
%pip install numpy
import numpy as np

In [12]:
big_list =  list(range(100000))
big_array = np.arange(100000)

In [8]:
%timeit [x ** 2 for x in big_list]

9.27 ms ± 1.37 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit big_array ** 2

85.9 μs ± 11.6 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### creating arrays

In [14]:
a = np.array([2,1,3,4])
print(a)

[2 1 3 4]


In [16]:
b = np.array([[3,4,5,1],[9,8,7,4]])# 2D array
print(b)

[[3 4 5 1]
 [9 8 7 4]]


In [17]:
a=np.array([0,0,0,0])
print(a)

[0 0 0 0]


In [19]:
zero = np.zeros((5,5))
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [27]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [28]:
print(np.eye(4))#identity matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
rng = np.random.default_rng(seed=2)
print(rng.random((2,3)))

[[0.26161213 0.29849114 0.81422574]
 [0.09191594 0.60010053 0.72856053]]


In [32]:
print(rng.integers(1,10,size=(3,3)))#unifrom

[[9 2 8]
 [1 6 3]
 [2 6 3]]


In [33]:
print(rng.normal(loc=0, scale=1,size=5))

[-0.31055655 -0.3288239  -0.79214676  0.45495807 -0.09919805]


### array attributes  and data types

In [36]:
M=np.array([[1,2,3],[4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
print(M.ndim)

2


In [39]:
print(M.shape)

(2, 3)


In [41]:
print(M.size)

6


In [42]:
print(M.dtype)

int32


In [47]:
ints = np.array([1,2,3], dtype=np.int64)

In [48]:
ints.dtype

dtype('int64')

In [52]:
floats = np.array([1,2,3],dtype=np.float64)
floats.dtype

dtype('float64')

### inedxing and slicing

In [53]:
x=np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [54]:
print(x[4])

14


In [56]:
print(x[4])

14


In [57]:
M=np.arange(1,13).reshape(3,4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
print(M[1,2])

7


In [61]:
M[0]
M[1]#prints the last input and variable

array([5, 6, 7, 8])

In [62]:
print(M[1])

[5 6 7 8]


In [63]:
print(M[2])

[ 9 10 11 12]


In [64]:
print(M[:,0])

[1 5 9]


### vector operation

In [65]:
a = np.array([1,2,3,4])
b=np.array([10,20,30,40])

In [67]:
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)

[1 2 3 4]
[10 20 30 40]
[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]


In [71]:
#Brodcasting

a = np.array([[1,2,3],
            [4,5,6]])
a.shape

(2, 3)

In [72]:
b = np.array([10,20,30])
b.shape

(3,)

In [73]:
print(a+b)

[[11 22 33]
 [14 25 36]]


In [74]:
a= np.array([[1,2],
             [3,4]])
a.shape

(2, 2)

In [75]:
b = np.array([1,1])
#  print(a+b) this is not going to run and its error cuz the order of those are not equal